syntax = "proto3";
import "nanopb.proto";

enum RobotState
{
  ROBOT_STATE_UNSPECIFIED = 0;
  ROBOT_STATE_MANUAL = 1;
  ROBOT_STATE_AUTO = 2;
  ROBOT_STATE_STAND_BY = 3;
  ROBOT_STATE_DOCKING = 4;
}

message Array3D
{
  sint32 x = 1;
  sint32 y = 2;
  sint32 z = 3;
}

message Angle
{
  float roll = 1;
  float pitch = 2;
  float yaw = 3;
}

message PowerStatus
{
  int32 voltage_mv = 1;
  int32 driver_current_ma = 2;
  int32 temperature = 3;
  int32 battery_capacity = 4;
  int32 battery_percent = 5;
  bool charging = 6;
  bool charger_detected = 7;
  int32 charging_current_ma = 8;
  int32 internal_temperature = 9;
}

message WakeUpConfig
{
  int32 hour = 1;
  int32 minutes = 2;
  optional bool sunday = 3;
  optional bool monday = 4;
  optional bool tuesday = 5;
  optional bool wednesday = 6;
  optional bool thursday = 7;
  optional bool friday = 8;
  optional bool saturday = 9;
}

message StandBy
{
  bool stand_by_connected = 1;
  bool stand_by_request = 2;
  bool stand_by_confirm = 3;
  int64 timestamp = 4;
  optional WakeUpConfig wake_up = 5;
}

message BuildInfo
{
  string commit_hash = 1 [(nanopb).max_size = 8];
  string branch_name = 2 [(nanopb).max_size = 30];
  string tag = 3 [(nanopb).max_size = 10];
  string build_date = 4 [(nanopb).max_size = 14];
}

message RobotHardware
{
  string robot_name = 1 [(nanopb).max_size = 15];
  string ecu_version = 2 [(nanopb).max_size = 10];
  string driver_version = 3 [(nanopb).max_size = 10];
  string motor_version = 4 [(nanopb).max_size = 10];
}

message TimeSync {
  uint64 t_mcu_send = 1; /**< ECU timestamp raw de envio em [us] */ 
  uint64 t_ros_recv = 2; /**< ROS timestamp de recebimento em [ns] */ 
  uint64 t_ros_send = 3; /**< ROS timestamp de envio em [ns] */
  uint64 t_mcu_recv = 4; /**< ECU timestamp raw de recebimento em [us] */
}

enum LEDSign
{
  LED_SIGN_UNSPECIFIED = 0;
  // Signos EMERGENCY_STOP até BATTERY_LOW reservados para uso interno da ECU, 
  // outros signos liberados
  reserved "LED_SIGN_EMERGENCY_STOP", "LED_SIGN_DISCONNECTED",
    "LED_SIGN_INTERNAL_FAILURE", "LED_SIGN_BOOTING", "LED_SIGN_BUMPER_HIT",
    "LED_SIGN_BATTERY_LOW";
  reserved 1 to 6;
  LED_SIGN_TURN_LEFT = 7;
  LED_SIGN_TURN_RIGHT = 8;
  LED_SIGN_MOVE_FW_LEFT = 9;
  LED_SIGN_MOVE_FW_RIGHT = 10;
  LED_SIGN_MOVE_BW_LEFT = 11;
  LED_SIGN_MOVE_BW_RIGHT = 12;
  LED_SIGN_MOVE_FORWARD = 13;
  LED_SIGN_MOVE_BACKWARD = 14;
  // TODO: Adicionar signo de relocalização
  // TODO: Adicionar signo de recuperação
}

message LEDRequest
{
  LEDSign sign = 1;
  bool active = 2;
}
