syntax = "proto3";
import "nanopb.proto";

enum CommandType
{
  COMMAND_TYPE_UNSPECIFIED = 0;
  COMMAND_TYPE_VELOCITY = 1;
  COMMAND_TYPE_ANGLE = 2;
  COMMAND_TYPE_TORQUE = 3;
}

enum OTAStatus
{
  OTA_STATUS_UNSPECIFIED = 0;
  OTA_STATUS_WAITING = 1;
  OTA_STATUS_CONNECTED = 2;
  OTA_STATUS_RUNNING = 3;
  OTA_STATUS_CONNECTION_TIMEOUT = 4;
  OTA_STATUS_BEGIN_UPDATE = 5;
  OTA_STATUS_ABORT_UPDATE = 6;
}

message OTAUpdate
{
  OTAStatus update = 1;
  string ssid = 2 [(nanopb).max_size = 50];
  string pwd = 3 [(nanopb).max_size = 50];
}

message OTAFeedback
{
  OTAStatus status = 1;
  string driver_ip = 2 [(nanopb).max_size = 20];
}

message MotorCommand { 
  float velocity = 1;
  float angle = 2;
  float torque = 3;
}

message DriverCommand
{
  int64 count = 1;
  bool enable = 2;
  CommandType type = 3;
  optional OTAUpdate ota_update = 4;

  optional MotorCommand left = 5;
  optional MotorCommand right = 6;
  optional MotorCommand single = 7;
  optional bool acknowledge_fault = 8;
}

message MotorStatus {
  float velocity = 1;
  float position = 2;
  float current = 3;
  uint32 error_code = 4;
  float temperature = 5;
  uint32 status = 6;
  bool running = 7;
  uint32 hall_state = 8;
}

enum EmergencyButtonStatus {
  EMERGENCY_BUTTON_STATUS_UNSPECIFIED = 0;
  EMERGENCY_BUTTON_STATUS_NONE = 1;
  EMERGENCY_BUTTON_STATUS_INPUT1 = 2;
  EMERGENCY_BUTTON_STATUS_INPUT2 = 3;
  EMERGENCY_BUTTON_STATUS_BOTH = 4;
}

message DriverFeedback
{
  int64 count = 1;
  int64 timestamp = 2;
  bool enabled = 3;
  optional OTAFeedback ota_feedback = 4;

  optional MotorStatus left = 5;
  optional MotorStatus right = 6;
  optional MotorStatus single = 7;

  optional EmergencyButtonStatus emergency_button = 8;
  float bus_voltage = 9;
  float temperature = 10;
  uint32 version = 11;
}
