syntax = "proto3";
import "aux.proto";
import "nanopb.proto";

message PIDConfig
{
  float k_p = 1;
  float k_i = 2;
  float k_d = 3;
}

message RobotParameters
{
  optional PIDConfig left_pid = 1;
  optional PIDConfig right_pid = 2;
  optional PIDConfig linear_pid = 3;
  optional PIDConfig angular_pid = 4;
  optional float wheel_diameter = 5;
  optional float wheel_distance = 6;
}

enum BumperID {
  BUMPER_ID_UNSPECIFIED = 0;
  BUMPER_ID_BUMPER_A = 1;
  BUMPER_ID_BUMPER_B = 2;
  BUMPER_ID_BUMPER_C = 3;
  BUMPER_ID_BUMPER_D = 4;
  BUMPER_ID_BUMPER_E = 5;
  BUMPER_ID_BUMPER_F = 6;
}

message Bumper
{
  bool status = 1;
  BumperID id = 2;
}

message Pose
{
  sint64 x_mm = 1;
  sint64 y_mm = 2;
  sint32 yaw_trad = 3;
  repeated double covariance = 4 [(nanopb).max_count = 36];
}

message Velocities
{
  sint32 linear_mm_s = 1;
  sint32 angular_trad_s = 2;
  repeated double covariance = 3 [(nanopb).max_count = 36];

  sint32 left_wheel_mm_s = 4;
  sint32 right_wheel_mm_s = 5;
}

message IMU
{
  Array3D acc = 1;
  Array3D gyro = 2;
  int32 temperature = 3;
}

message Encoder
{
  sint64 left = 1;
  sint64 right = 2;
  optional EncoderStatus left_status = 3;
  optional EncoderStatus right_status = 4;
  Pose pose_enc = 5;
  Velocities twist_enc = 6;

}

message EncoderStatus
{
  int32 magnitude = 1;
  int32 gain = 2;
  bool connected = 3;
  bool magnet_detected = 4;
  bool magnet_weak = 5;
  bool magnet_strong = 6;
  int32 ppr = 7;
}

message RobotInfo
{
  RobotHardware hardware_info = 1;
  int32 wheel_distance_mm = 2;
  int32 wheel_diameter_mm = 3;
  optional string debug_data = 4 [(nanopb).max_size = 500];
  optional BuildInfo build_data = 5;
  optional BuildInfo power_build_data = 6;
}

message FeedbackMessage
{
  repeated Bumper bumpers = 1 [(nanopb).max_count = 6];

  Pose pose = 2;
  Velocities velocities = 3;
  Encoder encoder = 4;
  IMU imu = 5;

  bool emergency_button_pressed = 6;
  bool colision_detected = 7;
  bool motion_detection = 8;

  PowerStatus power_status = 9;
  StandBy stand_by = 10;

  optional RobotParameters parameters = 11;
  optional RobotInfo info = 12;

  // true sempre que um comando opcional for recebido e foi corretamente
  // reconhecido. Comandos opcionais: RobotActions, RobotConfig, RobotState,
  // WakeUpConfig, timestamp
  optional bool last_command_ok = 13;
}
