# Serial port configuration
serial_port: "/dev/robot_ecu"
baud_rate: 1000000

# Timer configuration
reception_frequency: 500 # [Hz]
reconnection_frequency: 1 # [Hz]
command_frequency: 100 # [Hz]

# Custom function
fake_charging: False
fake_charging_radius: 0.5 # [m]
